"use client";
import React, { useState, useRef, useEffect } from 'react';
import { useChatStore } from '@/lib/store';
import { sendMessageToOpenRouter } from '@/lib/openrouter';
import { Mic, Send, StopCircle, Menu, Download, Trash2, PlusCircle, Copy, FileJson, FileText } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import Sidebar from './Sidebar';

export default function ChatInterface() {
  const { messages, addMessage, clearChat, mode, setMode, selectedModels, apiKey, setApiKey } = useChatStore();
  const [input, setInput] = useState('');
  const [isRecording, setIsRecording] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const abortControllerRef = useRef<AbortController | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);

  // --- ACTIONS ---
  const handleNewChat = () => {
    if (window.confirm("Start a new chat? Current history will be cleared (Export first if needed).")) {
        clearChat();
    }
  };

  const handleDownload = (format: 'txt' | 'json') => {
    let content = "";
    if (format === 'json') {
        content = JSON.stringify(messages, null, 2);
    } else {
        content = messages.map(m => `[${m.role.toUpperCase()} - ${m.modelName || 'User'}]\n${m.content}\n`).join('\n-------------------\n');
    }
    const blob = new Blob([content], { type: format === 'json' ? 'application/json' : 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chat-export-${new Date().toISOString().slice(0,10)}.${format}`;
    a.click();
    setShowExportMenu(false);
  };

  // --- LOGIC ---
  const startListening = () => {
    if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
      const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.onstart = () => setIsRecording(true);
      recognition.onend = () => setIsRecording(false);
      recognition.onresult = (event: any) => setInput((prev) => prev + " " + event.results[0][0].transcript);
      recognition.start();
    } else { alert("Browser does not support Speech Recognition."); }
  };

  const handleSend = async () => {
    if (!input.trim() || !apiKey) { if(!apiKey) alert("Enter API Key in the Sidebar first!"); return; }

    const userMsg = { id: uuidv4(), role: 'user' as const, content: input };
    addMessage(userMsg);
    setInput('');
    setIsGenerating(true);
    abortControllerRef.current = new AbortController();

    try {
        let currentHistory = messages.slice(-10).map(m => ({ role: m.role, content: m.content }));
        currentHistory.push({ role: 'user', content: userMsg.content });

        if (mode === 'roundtable') {
            // SEQUENTIAL LOGIC
            for (let i = 0; i < selectedModels.length; i++) {
                const modelId = selectedModels[i];
                const msgId = uuidv4();
                addMessage({ id: msgId, role: 'assistant', content: '', modelName: modelId });
                let fullResponse = "";

                const roundTableHistory = [...currentHistory];
                if (i > 0) {
                    roundTableHistory.push({
                        role: "user", 
                        content: `(System Note: The message above was generated by another AI model, ${selectedModels[i-1]}. Please critique it, add missing details, or offer a counter-perspective.)` 
                    });
                }

                await sendMessageToOpenRouter(
                    roundTableHistory,
                    modelId,
                    abortControllerRef.current!.signal,
                    (chunk) => {
                        fullResponse += chunk;
                        useChatStore.setState(state => ({
                            messages: state.messages.map(m => m.id === msgId ? { ...m, content: fullResponse } : m)
                        }));
                    }
                );
                currentHistory.push({ role: 'assistant', content: fullResponse });
            }
        } else {
            // PARALLEL LOGIC
            await Promise.all(selectedModels.map(async (modelId) => {
                const msgId = uuidv4();
                addMessage({ id: msgId, role: 'assistant', content: '', modelName: modelId });
                let fullResponse = "";
                
                await sendMessageToOpenRouter(
                    currentHistory, 
                    modelId,
                    abortControllerRef.current!.signal,
                    (chunk) => {
                        fullResponse += chunk;
                        useChatStore.setState(state => ({
                            messages: state.messages.map(m => m.id === msgId ? { ...m, content: fullResponse } : m)
                        }));
                    }
                );
            }));
        }

    } catch (error) { console.error(error); } 
    finally { setIsGenerating(false); }
  };

  const renderMessages = () => {
    const turns: any[] = [];
    let currentTurn: any = null;
    messages.forEach(msg => {
        if (msg.role === 'user') {
            if (currentTurn) turns.push(currentTurn);
            currentTurn = { user: msg, assistants: [] };
        } else if (currentTurn) {
            currentTurn.assistants.push(msg);
        }
    });
    if (currentTurn) turns.push(currentTurn);

    return turns.map((turn) => (
        <div key={turn.user.id} className="mb-12 border-b border-gray-800 pb-8">
            <div className="flex justify-end mb-6">
                <div className="bg-blue-600 text-white p-4 rounded-2xl rounded-br-none max-w-3xl shadow-lg text-lg">
                    {turn.user.content}
                </div>
            </div>
            <div className={`grid gap-6 ${mode === 'chat' ? 'grid-cols-1' : (selectedModels.length === 2 ? 'grid-cols-2' : 'grid-cols-3')}`}>
                {turn.assistants.map((msg: any) => (
                    <div key={msg.id} className="flex flex-col min-w-0">
                         <div className="flex items-center gap-2 mb-2">
                             <div className="w-2 h-2 rounded-full bg-blue-400"></div>
                             <span className="text-xs text-blue-300 font-bold uppercase tracking-wider truncate">{msg.modelName}</span>
                         </div>
                         <div className="bg-gray-800 border border-gray-700 p-5 rounded-2xl rounded-tl-none text-gray-200 shadow-md h-full whitespace-pre-wrap leading-relaxed overflow-x-auto text-sm">
                            {msg.content || <span className="animate-pulse text-gray-500">Thinking...</span>}
                         </div>
                    </div>
                ))}
            </div>
        </div>
    ));
  };

  return (
    <div className="flex h-screen bg-gray-950 text-white font-sans overflow-hidden">
      <Sidebar isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} />

      <div className={`flex-1 flex flex-col transition-all duration-300 ${isSidebarOpen ? 'ml-80' : 'ml-0'}`}>
        
        {/* HEADER TOOLBAR */}
        <div className="h-16 border-b border-gray-800 flex items-center justify-between px-6 bg-gray-900 shadow-sm z-10">
            <div className="flex items-center gap-4">
                <button onClick={() => setIsSidebarOpen(!isSidebarOpen)} className="p-2 hover:bg-gray-800 rounded-lg text-gray-400 hover:text-white transition-colors"><Menu size={20} /></button>
                
                {/* --- TITLE RESTORED HERE --- */}
                <h1 className="font-bold text-xl tracking-tight hidden sm:block mr-2">OpenStudio</h1>

                <div className="h-6 w-px bg-gray-700 mx-2 hidden sm:block"></div>
                
                <button onClick={handleNewChat} title="New Chat" className="flex items-center gap-2 text-sm font-medium text-gray-300 hover:text-white hover:bg-gray-800 px-3 py-1.5 rounded-lg transition-all">
                    <PlusCircle size={16} /> <span className="hidden md:inline">New Chat</span>
                </button>
            </div>
            
            <div className="flex items-center gap-3">
                 {/* Mode Switcher */}
                <div className="flex bg-gray-800 rounded-lg p-1 border border-gray-700">
                    {(['chat', 'versus', 'roundtable'] as const).map((m) => (
                        <button key={m} onClick={() => setMode(m)} className={`px-4 py-1.5 rounded-md capitalize text-xs font-medium transition-all ${mode === m ? 'bg-blue-600 text-white shadow' : 'text-gray-400 hover:text-gray-200'}`}>{m}</button>
                    ))}
                </div>

                {/* Export Menu */}
                <div className="relative">
                    <button onClick={() => setShowExportMenu(!showExportMenu)} className="p-2 hover:bg-gray-800 rounded-lg text-gray-400 hover:text-white transition-colors" title="Export Chat">
                        <Download size={20} />
                    </button>
                    {showExportMenu && (
                        <div className="absolute top-full right-0 mt-2 w-48 bg-gray-900 border border-gray-700 rounded-xl shadow-2xl p-1 z-50 animate-in fade-in zoom-in-95">
                            <button onClick={() => handleDownload('txt')} className="flex items-center gap-2 w-full px-4 py-2 text-sm text-gray-300 hover:bg-gray-800 rounded-lg text-left"><FileText size={16}/> Text File (.txt)</button>
                            <button onClick={() => handleDownload('json')} className="flex items-center gap-2 w-full px-4 py-2 text-sm text-gray-300 hover:bg-gray-800 rounded-lg text-left"><FileJson size={16}/> JSON Data (.json)</button>
                        </div>
                    )}
                </div>
            </div>
        </div>

        {/* CHAT AREA */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-8 scrollbar-thin scrollbar-thumb-gray-800 scrollbar-track-transparent">
            {messages.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full text-center space-y-4 opacity-50">
                    <div className="w-16 h-16 bg-gray-800 rounded-2xl flex items-center justify-center mb-4">
                        <PlusCircle size={32} className="text-blue-500" />
                    </div>
                    <h2 className="text-2xl font-bold text-gray-300">Welcome to OpenStudio</h2>
                    <p className="text-gray-500 max-w-md">Select models from the sidebar to begin.</p>
                </div>
            ) : renderMessages()}
            <div ref={bottomRef} />
        </div>

        {/* INPUT AREA */}
        <div className="p-6 bg-gray-950/80 backdrop-blur-lg border-t border-gray-800">
            <div className="max-w-5xl mx-auto flex gap-4 relative items-end">
                <button onClick={startListening} className={`p-4 rounded-2xl transition-all shadow-lg ${isRecording ? 'bg-red-500 animate-pulse text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-white'}`}><Mic size={24} /></button>
                <div className="flex-1 relative shadow-lg rounded-2xl bg-gray-800 focus-within:ring-2 focus-within:ring-blue-500/50 transition-all">
                    <textarea value={input} onChange={(e) => setInput(e.target.value)} className="w-full bg-transparent rounded-2xl p-4 text-white resize-none h-[64px] outline-none placeholder-gray-500 leading-relaxed" placeholder="Ask anything..." onKeyDown={(e) => { if(e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); }}} />
                </div>
                <button onClick={isGenerating ? () => abortControllerRef.current?.abort() : handleSend} className={`p-4 rounded-2xl shadow-lg transition-all transform active:scale-95 ${isGenerating ? 'bg-red-500 hover:bg-red-600' : 'bg-blue-600 hover:bg-blue-500'} text-white`}>
                    {isGenerating ? <StopCircle size={24} /> : <Send size={24} />}
                </button>
            </div>
            <div className="text-center mt-2 text-xs text-gray-600">
                {selectedModels.length} models active • {mode.toUpperCase()} Mode
            </div>
        </div>
      </div>
    </div>
  );
}